<?php
$fullMedian = $this->totals['full']['median'];
$fullAvg = $this->totals['full']['avg'];
$lastMedian = $this->totals['last']['median'];
$lastAvg = $this->totals['last']['avg'];

$fullMedian = ($fullMedian > 0) ? $fullMedian . ' Days' : '<div class="mt-12">N/A</div>';
$fullAvg = ($fullAvg > 0) ? $fullAvg . ' Days' : '<div class="mt-12">N/A</div>';
$lastMedian = ($lastMedian > 0) ? $lastMedian . ' Days' : '<div class="mt-12">N/A</div>';
$lastAvg = ($lastAvg > 0) ? $lastAvg . ' Days' : '<div class="mt-12">N/A</div>';

$fullChart = 0;
$fullChart += $this->outcomes['full']['win'];
$fullChart += $this->outcomes['full']['loss'];
$fullChart += $this->outcomes['full']['split'];
$fullChart += $this->outcomes['full']['other'];

$lastChart = 0;
$lastChart += $this->outcomes['last']['win'];
$lastChart += $this->outcomes['last']['loss'];
$lastChart += $this->outcomes['last']['split'];
$lastChart += $this->outcomes['last']['other'];

?>

<div class="col-xs-12 text-left">
  <h3 class="text-center OS-Bold"><?= $this->hearing; ?></h3>
  <h4 class="text-center OS-Bold fc-gray">Analytics Report</h4>
  <h5 class="text-center OS-Bold fc-gray"><?= $this->court; ?> - <?= $this->prArea; ?></h5>

  <div class="row mb-40-">
    <div class="col-xs-6">
      <div id="flowchartA" class="flowA flowchart">
        <div class="div-oval div-oval1">
          <p class="mt-3-"><?= $this->totals['full']['motions']; ?></p>
        </div>
        <div class="spn-font spn1">
          <span class="OS-Regular">Number of Motions Published</span>
          <br>
          <span class="OS-Bold">(<?= $this->minDate; ?> to present)</span>
        </div>
        <div class="line line1"></div>
        <div class="line line2"></div>
        <div class="line line3"></div>
        <div class="line line4"></div>
        <div class="line line5"></div>
        <div class="div-square div-square1 purple-color"><?= $fullAvg; ?></div>
        <div class="spn-font spn2">
          <span class="OS-Regular">Average Turnaround Time</span>
          <br>
          <span id="ml2010" class="OS-Bold">(<?= $this->minDate; ?> to present)</span>
        </div>
        <div class="div-square div-square2 purple-color"><?= $fullMedian; ?></div>
        <div class="spn-font spn3">
          <span class="OS-Regular">Median Turnaround Time</span>
          <br>
          <span class="OS-Bold">(<?= $this->minDate; ?> to present)</span>
        </div>
      </div>
    </div>

    <div class="col-xs-6">
      <div id="flowchartB" class="flowB flowchart">
        <div class="div-oval div-oval2"><p class="mt-3-"><?= $this->totals['last']['motions']; ?></p></div>
        <div class="spn-font spn4">
          <span class="OS-Regular">Number of Motions Published</span>
          <br>
          <span class="OS-Bold">(last 12 months)</span>
        </div>
        <div class="line line6"></div>
        <div class="line line7"></div>
        <div class="linecolor line line3"></div>
        <div class="line line4 linecolor"></div>
        <div class="line line5 linecolor"></div>
        <div class="div-square div-square1 blue-color"><?= $lastAvg; ?></div>
        <div class="spn-font spn5">
          <span class="OS-Regular">Average Turnaround Time</span>
          <br>
          <span class="att12 OS-Bold">(last 12 months)</span>
        </div>
        <div class="div-square div-square2 blue-color"><?= $lastMedian; ?></div>
        <div class="spn-font spn6">
          <span class="OS-Regular">Median Turnaround Time</span>
          <br>
          <span class="OS-Bold">(last 12 months)</span>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-xs-12 mb-20 mt-15-">
  <hr class="custom-hr">
</div>

<!-- Decision List Section -->
<div class="col-xs-12 text-left mb-20">
  <h5 class="text-left"><strong>Decisions Containing '<?= $this->hearing; ?>'</strong></h5>

  <div class="result-table-wrapper mt-5 mb-10">
    <table class="table table-bordered result-table result-table-header decision-table motion-list">
      <thead>
      <tr>
        <th>Decision Name</th>
        <th>Outcome for Moving Party/ies</th>
        <th>Decision Date</th>
        <th>Citation Number</th>
      </tr>
      </thead>
    </table>

    <table id="ha-decisions" class="table table-bordered result-table decision-table motion-list text-left">
      <?php if ($this->decisions && !empty($this->decisions)) { ?>
        <?= $this->partial('report/templates/hearing-analytics-decision-rows', [
          'result' => $this->decisions, 'decisionAccess' => $this->decisionAccess]);
        ?>
      <?php } else { ?>
        <tbody>
        <tr>
          <td colspan="4" class="text-center">There were no records found for your search criteria.</td>
        </tr>
        </tbody>
      <?php } ?>
    </table>
  </div>
  <u><a href="#" id="run-case-law">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      Click to see full list (Open in Case Law Search)
    </a></u>
</div>

<div class="col-xs-12 mb-20">
  <hr class="custom-hr">
</div>

<!-- Outcome Breakdowns Section (Charts) -->
<div class="col-xs-12 text-left mb-20">
  <p class="text-color"><?= $this->hearing; ?> Outcomes (for Moving Party)</p>

  <!-- pie chart(2010 to present) -->
  <div class="row">
    <div class="col-xs-12 col-md-6 container-border mb-20">
      <h3 class="text-center OS-Bold"><?= $this->minDate; ?> to Present</h3>

      <div id="container" class="chart-container <?= ($fullChart > 0) ? '' : 'no-results';?>">
        <?= ($fullChart > 0) ? '' : '<div class="fs-24 pt-30 text-center">No Results Found</div>'; ?>
      </div>
      <?php if ($fullChart > 0) { ?>
      <a href="#" id="run-full-outcome" class="text-center">
        <u><span class="glyphicon glyphicon-plus mt-15" aria-hidden="true"></span>
          Click to see full breakdown (open in Outcome Report)
        </u>
      </a>
      <?php } ?>
    </div>

    <!-- pie chart(Last 12 months) -->
    <div class="col-xs-12 col-md-6 mb-20">
      <h3 class="text-center OS-Bold">Last 12 months</h3>

      <div id="container2" class="chart-container ra <?= ($lastChart > 0) ? '' : 'no-results';?>">
        <?= ($lastChart > 0) ? '' : '<div class="fs-24 pt-30 text-center">No Results Found</div>'; ?>
      </div>
      <?php if ($lastChart > 0) { ?>
      <a href="#" id="run-outcome" class="text-center">
        <u><span class="glyphicon glyphicon-plus mt-15" aria-hidden="true"></span>
          Click to see full breakdown (open in Outcome Report)
        </u>
      </a>
      <?php } ?>
    </div>
  </div>

</div>

<div class="col-xs-12 mb-20">
  <hr class="custom-hr">
</div>

<!-- Judge/Master List Section -->
<div class="col-xs-8 col-xs-offset-2 text-left mb-20">
  <h4>Judge/Masters with the largest decision publication record
    for '<?= strtolower($this->hearing); ?>' in <?= $this->court; ?></h4>

  <div class="result-table-wrapper mt-5 mb-10">
    <table class="table table-bordered result-table result-table-header decision-table">
      <thead>
      <tr>
        <th>Judge Name</th>
        <th>Number of Motions Decisions Published (<?= $this->minDate; ?> - present)</th>
      </tr>
      </thead>
    </table>

    <table id="ha-judges" class="table table-bordered result-table decision-table text-left">
      <?php if ($this->judges && !empty($this->judges)) { ?>
        <?= $this->partial('report/templates/hearing-analytics-judge-rows', ['result' => $this->judges]); ?>
      <?php } else { ?>
        <tbody>
        <tr>
          <td colspan="2" class="text-center">There were no records found for your search criteria.</td>
        </tr>
        </tbody>
      <?php } ?>
    </table>
  </div>

  <b>Click a judge name to see their '<?= strtolower($this->hearing); ?>' decision list</b>
</div>

<?php if ($fullChart > 0) { ?>
<script>
  $(document).ready(function () {

    // Build the chart
    var fullChart = new CanvasJS.Chart("container",
      {

        chart: {
          height: 330
        },
        legend: {
          maxWidth: 350,
          itemWidth: 120
        },
        toolTip: {
          content: "{indexLabel}",
        },
        data: [
          {
            type: "pie",
            indexLabelFontSize: 18,
            showInLegend: false,
            legendText: "{indexLabel}",
            dataPoints: [
              {
                y: +'<?= $this->outcomes['full']['win']; ?>',
                indexLabel: "Win" + " (" + '<?= $this->outcomes['full']['win']; ?>' + "%)",
                color: "#8AEC00"
              },
              {
                y: +'<?= $this->outcomes['full']['loss']; ?>',
                indexLabel: "Loss" + " (" + '<?= $this->outcomes['full']['loss']; ?>' + "%)",
                color: "#FA1038"
              },
              {
                y: +'<?= $this->outcomes['full']['split']; ?>',
                indexLabel: "Split" + " (" + '<?= $this->outcomes['full']['split']; ?>' + "%)",
                color: "#50C2C3"
              },
              {
                y: +'<?= $this->outcomes['full']['other']; ?>',
                indexLabel: "Other" + " (" + '<?= $this->outcomes['full']['other']; ?>' + "%)",
                color: "#A349A4"
              }
            ]
          }
        ]
      });
    fullChart.render();
  });
</script>
<?php } ?>

<?php if ($lastChart > 0) { ?>
<script>
  $(document).ready(function () {
    var chart = new CanvasJS.Chart("container2",
      {

        chart: {
          height: 330
        },
        legend: {
          maxWidth: 350,
          itemWidth: 120
        },
        toolTip: {
          content: "{indexLabel}",
        },
        data: [
          {
            type: "pie",
            indexLabelFontSize: 18,
            showInLegend: false,
            legendText: "{indexLabel}",
            dataPoints: [
              {
                y: +'<?= $this->outcomes['last']['win']; ?>',
                indexLabel: "Win" + " (" + '<?= $this->outcomes['last']['win']; ?>' + "%)",
                color: "#8AEC00"
              },
              {
                y: +'<?= $this->outcomes['last']['loss']; ?>',
                indexLabel: "Loss" + " (" + '<?= $this->outcomes['last']['loss']; ?>' + "%)",
                color: "#FA1038"
              },
              {
                y: +'<?= $this->outcomes['last']['split']; ?>',
                indexLabel: "Split" + " (" + '<?= $this->outcomes['last']['split']; ?>' + "%)",
                color: "#50C2C3"
              },
              {
                y: +'<?= $this->outcomes['last']['other']; ?>',
                indexLabel: "Other" + " (" + '<?= $this->outcomes['last']['other']; ?>' + "%)",
                color: "#A349A4"
              }
            ]
          }
        ]
      });
    chart.render();
  });
</script>
<?php } ?>